# Configuration Nixpacks pour Railway
# https://nixpacks.com/docs/configuration/file

[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = ["npm install --legacy-peer-deps --omit=dev"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm run start:prod"

[variables]
NODE_ENV = "production"
